### ISSUE TITLE
27th of May. The Minskins

### ISSUE THREAD

**Issue by WinterCore** [wrakc/smashing-magazine#1]
The project looks really nice ╰(*°▽°*)╯. However, here are some recommendations/suggestions.
Change:
- MInimize/Merge redundant CSS rules.
- Check out https://animate.style/.
- Just a reminder to clean up the empty class attributes in the HTML. 😀

Good luck on finishing the project.

And here's a bunny.
<pre>
     / \
    / _ \
   | / \ |
   ||   || _______
   ||   || |\     \
   ||   || ||\     \
   ||   || || \    |
   ||   || ||  \__/
   ||   || ||   ||
    \\_/ \_/ \_//
   /   _     _   \
  /               \
  |    O     O    |
  |   \  ___  /   |
 /     \ \_/ /     \
/  -----  |  -----  \
|     \__/|\__/     |
\       |_|_|       /
 \_____       _____/
       \     /
       |     |

</pre>

**Comment by carlosveigadev** [comment]
Thanks for the suggestions guys!
It helped a lot! 
:heart:
