### ISSUE TITLE
Smashing Magazine review

### ISSUE THREAD

**Issue by eliasecasta** [wrakc/smashing-magazine#2]
Good job so far Victor! Your page is looking really good right now, we have a couple improvements that you can add to it:

- Try to use best practices and be less repetitive in your code. (DRY method)
- Remember to use a lot of contrast between areas (for ex: if you used a gray2 in the past div background, don't use a gray3 for the next div but try to use a gray4 or even gray5 as you see them fit best)

Keep it going!

**Comment by Victorgonbu** [comment]
Thank for all sugentions Elias, we made them real!
